use_frameworks!

platform :ios, '8.0'

target 'LHAlertController_Example' do
  pod 'LHAlertController', :path => '../'

  target 'LHAlertController_Tests' do
    inherit! :search_paths

    
  end
end
